server:
  port: 8080
spring:
  datasource:
    name: xiaomi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 115605Liu
    url: jdbc:mysql://localhost:3306/xiaomi?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true

  # Redis 配置
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        # 连接池中的最小空闲连接数
        min-idle: 0
        # 连接池中的最大空闲连接数
        max-idle: 8
        # 连接池的最大活跃连接数
        max-active: 20
        # 连接池最大阻塞等待时间，使用 PT 表示 Duration 格式
        max-wait: -1ms

jackson:
  date-format: yyyy-MM-dd HH:mm:ss

rabbitmq:
  host: localhost
  port: 5672   # 默认端口
  username: guest
  password: guest

mybatis-plus:
  # mapper XML 位置
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或分号分隔
  type-aliases-package: com.mall.xiaomi.entity
  global-config:
    db-config:
      # 主键类型
      id-type: auto
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 自动驼峰命名
    map-underscore-to-camel-case: true


jwt:
  secret: "MTE1NjA1THV1L2J1aWxkX3JlbGF0ZWQvSmF2YV9ob3VkdWFuL2phdmFfcHJvamVjdC9sb25ndG91LXBsdXM="
  issuer: "longtou"
  expiration: 7200
